/** Runtime identities generated by public candidate f176107 before authored encounter profiles. */
export const PRE_PROFILE_E1M1_RUNTIME_FIXTURE = {
  sourceCommit: 'f1761073a869a4f4d82e22b8bb1a0c27e380734a',
  actor: {
    uid: 'enemy-1',
    kind: 'enemy',
    id: 'returned-mail',
    health: 0,
    dead: true,
    scoreEligible: false,
    phaseLocked: false,
    position: [37.5, 0, 37.5],
    awake: false,
  },
  behavior: {
    version: 1,
    elapsed: 4,
    nextEntityId: 3,
    actors: [{
      uid: 'enemy-1',
      hostileId: 'returned-mail',
      cooldown: .2,
      attackCursor: 1,
      phaseIndex: 0,
      phaseId: 'base',
      bobClock: 4,
      visible: true,
      revealRemaining: 0,
      strafeSign: 1,
      action: 'dead',
      stateTimer: 0,
      targetUid: 'player',
      redacted: false,
      lungeRemaining: 0,
    }],
    projectiles: [{
      id: 'projectile-2', ownerUid: 'enemy-1', ownerId: 'returned-mail', kind: 'returned-mail-shot',
      position: { x: 37.5, y: .6, z: 37.5 }, velocity: { x: -2, y: 0, z: -1 }, radius: .1,
      damage: 10, damageKind: 'impact', remaining: 1, targetUid: 'player', homing: 0,
    }],
    hazards: [{
      id: 'hazard-1', ownerUid: 'enemy-1', ownerId: 'returned-mail', kind: 'paper-snag',
      position: { x: 36, y: 0, z: 36 }, radius: 1, damage: 5, damageKind: 'hazard',
      remaining: 2, armRemaining: 0, pulseRemaining: .5, pulseInterval: 1, armed: true,
    }],
    pendingSounds: [{ position: { x: 37.5, y: 0, z: 37.5 }, radius: 8, sourceUid: 'enemy-1' }],
    pendingDamage: [{ targetUid: 'player', sourceUid: 'enemy-1', amount: 10 }],
  },
  // Published schema-1 saves stored only these mutable pickup fields. At this
  // UID the public build placed counted Night Goggles; the new profile places a weapon.
  pickup: {
    uid: 'pickup-38',
    collected: true,
    phaseLocked: false,
  },
  pickupPlacement: {
    kind: 'pickup',
    id: 'night-inspection-goggles',
    position: [40.5, 0, 40.5],
  },
  tally: { kills: 1, totalKills: 21, items: 1, totalItems: 1, secrets: 0, totalSecrets: 2, elapsed: 40 },
} as const;
