"""Write a reproducible runtime inventory and concise production status document."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / "assets/public_runtime"
RUNTIME_AUDIO = ROOT / "assets/audio"
MANIFEST = ROOT / "manifests/runtime-inventory.json"
DOCUMENT = ROOT / "ASSET_PRODUCTION_STATUS.md"


CATEGORIES = (
    "enemies", "bosses", "weapons", "pickups", "effects", "textures", "props", "skies", "ui", "fonts",
)


def family_count(path: Path) -> int:
    return sum(1 for child in path.iterdir() if child.is_dir()) if path.exists() else 0


def main() -> None:
    categories = {}
    for name in CATEGORIES:
        path = RUNTIME / name
        categories[name] = {
            "png": len(list(path.rglob("*.png"))) if path.exists() else 0,
            "json": len(list(path.rglob("*.json"))) if path.exists() else 0,
            "top_level_families": family_count(path),
        }
    validation_path = ROOT / "manifests/art-library-validation.json"
    validation = json.loads(validation_path.read_text(encoding="utf-8")) if validation_path.exists() else {}
    audio_validation_path = ROOT / "manifests/audio-library-validation.json"
    audio_validation = json.loads(audio_validation_path.read_text(encoding="utf-8")) if audio_validation_path.exists() else {}
    audio_files = list(RUNTIME_AUDIO.rglob("*.mp3")) if RUNTIME_AUDIO.exists() else []
    audio = {
        "music_tracks": len(list((RUNTIME_AUDIO / "music").glob("*.mp3"))) if RUNTIME_AUDIO.exists() else 0,
        "sfx_sprites": len(list((RUNTIME_AUDIO / "sfx").glob("*.mp3"))) if RUNTIME_AUDIO.exists() else 0,
        "sfx_cues": audio_validation.get("sfx", {}).get("cueCount", 0),
        "semantic_groups": audio_validation.get("sfx", {}).get("groupCount", 0),
        "bytes": sum(path.stat().st_size for path in audio_files),
    }
    payload = {
        "runtime_root": RUNTIME.relative_to(ROOT).as_posix(),
        "categories": categories,
        "total_png": sum(item["png"] for item in categories.values()),
        "validation_passed": validation.get("passed", False),
        "audio": audio,
        "audio_validation_passed": audio_validation.get("passed", False),
    }
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(payload, indent=2) + "\n", encoding="ascii")

    lines = [
        "# Asset Production Status",
        "",
        "This file is generated by `python tools/write_asset_status.py`. Runtime images live under `assets/public_runtime`, runtime audio lives under `assets/audio`, and editable generation stages live under `art/source` plus the audio source spec.",
        "",
        "## Current Inventory",
        "",
        "| Category | Runtime PNGs | Metadata JSON | Top-level families |",
        "|---|---:|---:|---:|",
    ]
    for name, item in categories.items():
        lines.append(f"| {name} | {item['png']} | {item['json']} | {item['top_level_families']} |")
    lines.extend([
        "",
        f"Total runtime PNGs: **{payload['total_png']}**.",
        "",
        "## Audio Inventory",
        "",
        "| Music tracks | SFX sprite shards | Unique SFX cues | Semantic groups | Encoded size |",
        "|---:|---:|---:|---:|---:|",
        f"| {audio['music_tracks']} | {audio['sfx_sprites']} | {audio['sfx_cues']} | {audio['semantic_groups']} | {audio['bytes'] / (1024 * 1024):.2f} MiB |",
        "",
        "## Source Authority",
        "",
        "1. `art/source/imagegen`: immutable generated originals.",
        "2. `art/source/keyed`: original keyed copies used to identify the intended key color.",
        "3. `art/source/alpha`: chroma-removed intermediates.",
        "4. `art/source/alpha/normalized`: the only source consumed by runtime sprite builders.",
        "5. `art/source/keyed/normalized`: exact-key, evenly spaced review sheets rebuilt from normalized alpha.",
        "6. `assets/public_runtime`: fixed-canvas, palette-locked shipping images.",
        "7. `manifests/audio-production-spec.json`: authored track motifs, arrangements, identities, and SFX variant scope.",
        "8. `tools/build_audio_library.py`: deterministic lossless audio source renderer.",
        "9. `assets/audio`: compressed shipping music and independently decoded semantic SFX sprite shards.",
        "",
        "## Consistency Gate",
        "",
        f"Latest art validation: **{'PASS' if payload['validation_passed'] else 'FAIL OR NOT RUN'}**.",
        f"Latest audio validation: **{'PASS' if payload['audio_validation_passed'] else 'FAIL OR NOT RUN'}**.",
        "",
        "Run `python tools/normalize_chroma_sheets.py` followed by `python tools/validate_art_library.py`. Any missing logged generation original, keyed-copy checksum mismatch, unregistered sheet, missing stage pair, non-exact keyed border, chroma spill, off-center cell, baseline drift, wrong image mode, palette leak, or actor metadata mismatch blocks approval.",
        "",
        "Run `py -3.11 tools/build_audio_library.py --force`, then the audio content contract. Missing media, invalid duration, duplicate motifs or cue fingerprints, unsafe levels, missing shard assignments, overlapping regions within a sprite shard, altered hashes, or incomplete semantic definition references block approval.",
        "",
        "## Identity Rule",
        "",
        "All shipping art uses the fictional red-ledger identity described in the production bible. Generated text and third-party names or marks are prohibited; narrative copy is rendered separately with the original bitmap font.",
        "",
    ])
    DOCUMENT.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {DOCUMENT.name} with {payload['total_png']} runtime PNGs")


if __name__ == "__main__":
    main()
